version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: scripts/deploy_to_chrome_web_store.sh aodjmnfhjibkcdimpodiifdjnnncaafh PROD # build chrome version and push to chrome store, but only if version number > chrome store version
#     - run: scripts/deploy_to_chrome_web_store.sh pbnihbeifpolhmekheiedlelddoagook BETA
